justfound/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web_board.urls", namespace='web_board')),
    path('martor/', include('martor.urls')),
]

web_board/urls.py
from django.urls import path

from .views import index, history, post_detail, tg_login, ManifestView


app_name = "web_board"

urlpatterns = [
    path("", index, name="index"),
    path("history/", history, name="history"),
    path("history/<int:post_id>/", post_detail, name="post_detail"),
    path("tg_login/", tg_login),
    path("manifest/", ManifestView.as_view(), name="manifest")
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class TgUser(AbstractUser):
    tg_username = models.CharField(max_length=200)
    photo_url = models.URLField(default="")

    def __str__(self):
        return f"{self.username}:{self.tg_username}"

web_board/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from martor.models import MartorField

from telegram_group_poster.utils import send_message

User = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    text = MartorField(verbose_name="Полный текст")
    tg_text = MartorField(verbose_name="Текст для телеграмма", blank=True, default=" ")
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации")
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор"
    )
    is_posted = models.BooleanField(default=False, blank=False, null=False)

    def make_full_markdown_post(self):
        return settings.POST_TEMPLATE.format(self.title, self.tg_text, settings.SITE_HOST, self.get_absolute_url())

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('web_board:post_detail', kwargs={'post_id': self.pk})

    def save(
            self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        super().save(force_insert, force_update, using, update_fields)
        if not self.is_posted:
            self.is_posted = True
            send_message(self.make_full_markdown_post())

    class Meta:
        get_latest_by = ("pub_date",)
        ordering = ("-pub_date",)
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def __str__(self):
        return f"{self.title} at {self.pub_date}"

web_board/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse, HttpResponsePermanentRedirect, render, get_object_or_404
from django.views.generic import TemplateView

from users.utils import validate_auth_data
from telegram_group_poster.utils import send_message
from .models import Post


def index(request):
    post = Post.objects.select_related("author").latest()
    return render(request, "web_board/page.html", {"post": post})


def history(request):
    posts = Post.objects.select_related("author")
    return render(
        request,
        "web_board/history.html",
        {'posts': posts}
    )


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, "web_board/page.html", {"post": post})


@login_required
def send(request):
    send_message("Сообщение, **отправленное с сайта**")
    return HttpResponse("Отправлено")


def tg_login(request):
    auth_data = dict(request.GET.items())
    if not validate_auth_data(auth_data):
        return HttpResponse('Wrong auth data. Check it and try again')
    user = authenticate(username=auth_data['username'])
    login(request, user)
    return HttpResponsePermanentRedirect('/admin')


class ManifestView(TemplateView):
    template_name = "web_board/manifest.html"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Получай новые знания в IT, электронике, науке вместе со мной">
    <meta name="keywords" content="IT, наука, программирование, электроника">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@900&display=swap" rel="stylesheet">
    <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet"/>
    <link href="{% static 'martor/css/martor.bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet"/>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/overrided_styles.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<main>
    <div class="container">
        <div class="page py-4">
            {% block content %}{% endblock %}
        </div>
    </div>
    <footer class="pt-3">
        <div class="footer__nav text-center ">
            <ul class="nav justify-content-center  align-items-center">
                {% block is_manifest %}
                <li class="nav-item"><a class="nav-link" href="{% url "web_board:manifest" %}">Манифест</a></li>
                {% endblock %}
                <li class="nav-item>">
                    <div>
                        <script async src="https://telegram.org/js/telegram-widget.js?19"
                                data-telegram-login="justfoundru_bot"
                                data-size="small" data-auth-url="http://justfound.ru/tg_login" data-request-access="write"></script>
                    </div>
                </li>
            </ul>
        </div>
    </footer>
</main>
<script type="text/javascript" src="{% static 'plugins/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
<script>
    $('.page__content pre').each(function (i, block) {
        hljs.highlightBlock(block);
    });
</script>
</body>
</html>

templates/web_board/history.html
{% extends 'base.html' %}

{% block title %}АРХИВ - Недавно нашел!{% endblock %}

{% block content %}
    {% regroup posts by pub_date|date:"F y" as months %}
    {% for m in months %}
        <h1 class="py-3 px-5">{{ m.grouper }}</h1>
        {% for post in m.list %}
            <p><span class="px-5 text-secondary">{{ post.pub_date|date:"d" }}</span><a href="{% url "web_board:post_detail" post.pk %}">{{ post.title }}</a></p>
        {% endfor %}
    {% endfor %}
{% endblock %}

templates/web_board/includes/page_footer.html
<div class="page__info_bottom row pt-5 px-5 ">
    <div class="page_date col-auto me-auto text-secondary">{{ post.pub_date}}</div>
    <nav class="page_nav col-auto offset-md-4">
        <div class="row text-center">
            <nav class="col-auto align-middle">
                <ul class="pagination">
                {% if post.get_previous_by_pub_date %}
                    <li class="page-item"><a class="page-link" href="{% url "web_board:post_detail" post.get_previous_by_pub_date.pk %}"><i class="bi bi-arrow-left"></i></a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href=""><i class="bi bi-arrow-left"></i></a></li>
                {% endif %}
                {% if post.get_next_by_pub_date %}
                    <li class="page-item"><a class="page-link" href="{% url "web_board:post_detail" post.get_next_by_pub_date.pk %}"><i class="bi bi-arrow-right"></i></a></li>
                {% else %}
                    <li class="page-item"><a class="page-link disabled" href=""><i class="bi bi-arrow-right"></i></a></li>
                {% endif %}
                </ul>
            </nav>
        </div>
    </nav>
</div>

templates/web_board/includes/page_header.html
<div class="px-5 page__info_top row">
    <div class="page_date col-auto me-auto pb-3 text-secondary">{{ post.pub_date }}</div>
    <nav class="page_nav col-auto">
        <div class="row  text-center">
            <div class="page_nav__archive col-auto"><a href="{% url 'web_board:history' %}">Архив</a></div>
            <div class="page_nav__tg col-auto">
                <a href="https://t.me/justfound_ru" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-telegram" viewBox="0 0 16 16">
                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"/>
                    </svg>
                </a>
            </div>
        </div>
    </nav>
</div>

templates/web_board/manifest.html
{% extends "base.html" %}

{% block title %}
Манифест
{% endblock %}

{% block content %}
  <div class="page__title pb-5 pt-3 px-5 "><h1>Манифест</h1></div>
  <div class="page__content px-5 ">
    <p>Как красиво названа страничка "Обо мне", правда?</p>
    <p>Этот ресур, смотря не его название, служит хранилищем недавно полученных знаний и сведений. Не относящихся к политике.
    Уникальность ресурса -- тут отлично сочетаются IT, юмор, медицина, технические науки, история. В общем, солянка. Параллельно с публикацией на сайте, все посты
    попадают в телеграмм-канал <a href="https://t.me/justfound_ru">@justfound_ru</a>. Заходите, буду рад :)</p>
    <p>В общем, добро пожаловать. Если интересна связь со мной, то вы найдете контакты в группе, указанной выше.</p>
    <p>Не могу не сказать спасибо за вдохновение сайту <a href="https://снми.рф">снми.рф</a> за дизайн и структуру. Сам я начисто лишен чувства прекрасного.</p>
  </div>
{% endblock %}

{% block is_manifest %}
  <li class="nav-item"><a class="nav-link" href="{% url "web_board:index" %}">Главная</a></li>
{% endblock %}

templates/web_board/page.html
{% extends 'base.html' %}
{% load static %}
{% load martortags %}

{% block title %}{{ post.title|upper }} - Недавно нашел!{% endblock %}
{% block content %}

    {% include 'web_board/includes/page_header.html' %}
    <div class="page__title pb-5 pt-3 px-5"><h1>{{ post.title }}</h1></div>
    <div class="page__content px-5 ">
        {{ post.text|safe_markdown }}
    </div>
    {% include 'web_board/includes/page_footer.html' %}
    </div>

{% endblock %}